### PR TITLE
to be compatible with miniAOD maker

### PR DESCRIPTION
**Pull request by jshlee**
Hi,

How come electronIDValueMapProducer is removed from egmGsfElectronIDSequence?
This makes the miniAOD maker to break, I guess one or the other should be updated.

Also, when will this be PR to official cmssw?

Regards,
Jason.

### CODE REVIEW

**Comment by ikrav** [comment]
Hi Jason,

I do not understand GitHub mechanics well enough, I am confused.

Did you create a pull request? Why? What are you trying to do?

Please note that all these changes are being integrated into the present nearest
74X and 750 (maybe 74X is already done, do not know what is X) by Lindsey.
It is done via one of his branches that was in sync with my emg_id_74X_v0/v1 a few days
ago, but by now may have evolved.

The ElectronIDValueMapProducer is removed because it is no longer necessary. 
For 70X, certain electron quantities were not part of the GsfElectron and had to be
computed by a producer. It is not the case already in 72X (but the producer was still
there in 72X), and we are now removing the invocation of the producer.

Cheers,
Ilya

**Comment by jshlee** [comment]
Hi Ilya,

I made this PR because switchOnVIDElectronIdProducer wasn't working with miniAOD maker
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L150

Regards,
Jason.

**Comment by lgray** [comment]
@jshlee please copy/paste here the configuration you are using. It may be the case you are using an old and deprecated ID that is not updated to the latest tuning (which do not require the valuemap producer).

**Comment by jshlee** [comment]
Hi Lindsey and Ilya,

I'm trying to run PhysicsTools/PatAlgos/test/patMiniAOD_standard_cfg.py in 74X or 75X nightly.

The following lines don't work in miniAOD_tools.py
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L150-L160

because switchOnVIDElectronIdProducer needs two inputs (hence this pr)
and because electronIDValueMapProducer is no longer used

PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py will need updating too.

Regards,
Jason.

**Comment by lgray** [comment]
@jshlee ah, have you added the PR https://github.com/cms-sw/cmssw/pull/9002 that is presently in testing?

Please do `git cms-merge-topic 9002` from the _latest_ nightly and try again.

**Comment by jshlee** [comment]
Just to make sure, should the following lines be removed?
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L153-L160

I'll do a few tests and submit a new pr based on 9002.

**Comment by lgray** [comment]
Hi Jason,

If you merge the pull request those lines are modified appropriately.

-Lindsey

**Comment by ikrav** [comment]
Ken, here are Natasha’s questions in full (including the 2-page proposal
of her thesis). She is interested to get an opinion of a Literature professor,
as you see in her email, why nobody is interested to help, and whether
any of the considerations she lists could be factors why.

What she was asking from the KU professors was something like (I think):
  1) ask their students to read ~10-page short story by a famous writer
  2) ask them to write a short essay or do a reading quiz
  3) do a questionnaire soon after
  4) do another questionnaire at the end of the semester.

If Sarah has any thoughts, anything would be helpful. But if she is too busy
to think about it, this is fine too, don’t hesitate to say no.

Thanks
Ilya


> Begin forwarded message:
> 
> From: "Kravchenko, Natasa" <nkrav@ku.edu>
> Date: October 26, 2015 at 8:42:32 AM CDT
> To: "ikrav@unl.edu" <ikrav@unl.edu>
> Subject: the literature question
> 
> 
> 
> So this is the proposal that I wrote. The questions are as follows:
> 
> Although this proposal earned a summer fellowship, my advisor and I are having difficulty finding people from the Literature department who are willing to let us collect data in their classes. In asking KU Literature instructors, my advisor has gotten some rejections and some non-answers. She was unable to tell whether the non-answers were the result of people not understanding our design (and not wanting to ask for clarification, for some reason), or from their reluctance to reject us in a straightforward fashion. I would really appreciate some help in understanding why this might be the case. It would be helpful if a Literature scholar would look over the proposal and honestly tell me their reaction.
> 
> I was told that part of this may be the discipline-wide negative attitude toward measuring things that have to do with literature or instruction, that collecting quantitative data is something people dislike and oppose within the discipline. Apparently, the field has had to fight to avoid having to use of measurement and quantification, so they are not going to be happy to do something they had to fight against.
> 
> A Comp & Rhet graduate student offered that, in addition to the disciplinary tastes, there are barriers associated with the administration/management side of teaching: people are concerned about class time (survey classes) and fitting my stuff in would make things more difficult. I was also told something about personal status and standing within the university (individuals with lower status may be less likely to agree to help out).
> 
> Obviously, these barriers may be insurmountable and I may have to throw out this proposal or make major changes to it. Before taking the drastic steps, it’d be great if I could to get more feedback, so that I know exactly what I am dealing with. The proposal is not particularly detailed and I am not asking for extensive feedback (though I would not turn it down). I am just wondering how this looks to someone who teachers a college-level literature class, what kind of thoughts does it bring up.
> 
> 

>

**Comment by lgray** [comment]
@ikrav I think you sent this mail to the wrong place...

**Comment by ikrav** [comment]
Sorry everyone, my previous post was a personal email that ended up here somehow. Grant proposal writing has messed with my head...

**Pull request closed without merging**
