### PR TITLE
Savvas' Effective Areas for latest egm ID campaign

### PR DESCRIPTION
**Pull request by lgray**
@skyriacoCMS

### CODE REVIEW

**Comment by lgray** [comment]
@skyriacoCMS Could you possible also prepare a pull request with the new data/Spring15 area to the following git repository? https://github.com/cms-data/RecoEgamma-PhotonIdentification

All you need to do is add the effective areas to the Spring15 directory in this repository and then tell me when it is ready. I can then make a pull request for updating the central afs areas.

**Comment by skyriacoCMS** [comment]
Hey Lindsey,

I have forked and added the EA's

https://github.com/skyriacoCMS/RecoEgamma-PhotonIdentification/tree/patch-1/Spring15

-Savvas

**Comment by skyriacoCMS** [comment]
Also this is my skype if in anycase would make things easier.

savvas.kyriacou88

-Savvas

**Comment by skyriacoCMS** [comment]
Hey Lindsey,

I have forked and added the EA's

https://github.com/skyriacoCMS/RecoEgamma-PhotonIdentification/tree/patch-1/Spring15

-Savvas

**Comment by lgray** [comment]
Thanks Savvas!

**Pull request merged**
